set(_CATKIN_CURRENT_PACKAGE "pso_planner_pkg")
set(pso_planner_pkg_VERSION "0.1.0")
set(pso_planner_pkg_MAINTAINER "chp <chp@todo.todo>")
set(pso_planner_pkg_PACKAGE_FORMAT "1")
set(pso_planner_pkg_BUILD_DEPENDS "roscpp" "std_msgs" "msg_pkg")
set(pso_planner_pkg_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "msg_pkg")
set(pso_planner_pkg_BUILDTOOL_DEPENDS "catkin")
set(pso_planner_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(pso_planner_pkg_EXEC_DEPENDS "roscpp" "std_msgs" "msg_pkg")
set(pso_planner_pkg_RUN_DEPENDS "roscpp" "std_msgs" "msg_pkg")
set(pso_planner_pkg_TEST_DEPENDS )
set(pso_planner_pkg_DOC_DEPENDS )
set(pso_planner_pkg_URL_WEBSITE "")
set(pso_planner_pkg_URL_BUGTRACKER "")
set(pso_planner_pkg_URL_REPOSITORY "")
set(pso_planner_pkg_DEPRECATED "")