set(_CATKIN_CURRENT_PACKAGE "genetic_algorithm_pkg")
set(genetic_algorithm_pkg_VERSION "0.1.0")
set(genetic_algorithm_pkg_MAINTAINER "chp <chp@todo.todo>")
set(genetic_algorithm_pkg_PACKAGE_FORMAT "1")
set(genetic_algorithm_pkg_BUILD_DEPENDS "roscpp" "std_msgs" "msg_pkg")
set(genetic_algorithm_pkg_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "msg_pkg")
set(genetic_algorithm_pkg_BUILDTOOL_DEPENDS "catkin")
set(genetic_algorithm_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(genetic_algorithm_pkg_EXEC_DEPENDS "roscpp" "std_msgs" "msg_pkg")
set(genetic_algorithm_pkg_RUN_DEPENDS "roscpp" "std_msgs" "msg_pkg")
set(genetic_algorithm_pkg_TEST_DEPENDS )
set(genetic_algorithm_pkg_DOC_DEPENDS )
set(genetic_algorithm_pkg_URL_WEBSITE "")
set(genetic_algorithm_pkg_URL_BUGTRACKER "")
set(genetic_algorithm_pkg_URL_REPOSITORY "")
set(genetic_algorithm_pkg_DEPRECATED "")